apiVersion: v1
kind: ConfigMap
metadata:
  name: prompt-config
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  prompt.yaml: |-
{{ .Files.Get "files/prompt.yaml" | indent 4 }}
